# Generated by Django 5.0 on 2024-10-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprojectfile',
            name='project',
        ),
        migrations.DeleteModel(
            name='AdminProject',
        ),
        migrations.DeleteModel(
            name='AdminProjectFile',
        ),
    ]
