# Generated by Django 5.0 on 2024-10-25 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_adminprojectfile_project_delete_adminproject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfileadmin',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectAdmin',
        ),
        migrations.DeleteModel(
            name='ProjectFileAdmin',
        ),
    ]
