# Generated by Django 5.0 on 2024-10-25 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_remove_projectfileadmin_project_delete_projectadmin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
    ]
